esm modules in node are impossible to understand
* include the file extension (e.g. '.js') for ALL relative imports
* change package.json "type" to "module"
* define a __dirname replacement, because otherwise:

> ReferenceError: __dirname is not defined in ES module scope.
>
> This file is being treated as an ES module because it has a '.js' file
> extension and '/app/package.json' contains "type": "module". To treat
> it as a CommonJS script, rename it to use the '.cjs' file extension.